print("Welcome to the tip calculator.")
bill = float(input(f"What was the total bill? $"))
tip = int(input(("What percentage tip would you like to give? 10,12 or 15? ")))
People = int(input("How many people to split the bill?"))
pay = (((bill*(tip/100))+bill)/People)
print(pay)